allvars=['runId',
             'lumiSection',
             'eventId',
             'isData',
             'mcWeight',

             'pu_nTrueInt',
             'pu_nPUVert',

             'pfMetCorrPt',
             'pfMetCorrPhi',
             'pfMetCorrUnc',

             'nEle',
             'elePx',
             'elePy',
             'elePz',
             'eleEnergy',
             'eleIsPassVeto',
             'eleIsPassLoose',
             'eleIsPassTight',
             'eleCharge',

             'nPho',
             'phoPx',
             'phoPy',
             'phoPz',
             'phoEnergy',
             'phoIsPassLoose',
             'phoIsPassTight',

             'nMu',
             'muPx',
             'muPy',
             'muPz',
             'muEnergy',
             'isLooseMuon',
             'isTightMuon',

             'PFIsoLoose', #-- < 0.25
             'PFIsoMedium', #-- < 0.20
             'PFIsoTight', #-- < 0.15
             'PFIsoVeryTight', #-- < 0.10
             'muCharge',

             'HPSTau_n',
             'HPSTau_Px',
             'HPSTau_Py',
             'HPSTau_Pz',
             'HPSTau_Energy',
             'disc_decayModeFinding',
             'disc_againstElectronLooseMVA6',
             'disc_againstElectronMediumMVA6',
             'disc_againstElectronTightMVA6',
             'disc_againstMuonLoose3',
             'disc_againstMuonTight3',
             'disc_byVLooseIsolationMVArun2017v2DBoldDMwLT2017',
             'disc_byLooseIsolationMVArun2017v2DBoldDMwLT2017',
             'disc_byMediumIsolationMVArun2017v2DBoldDMwLT2017',
             'disc_byTightIsolationMVArun2017v2DBoldDMwLT2017',

             'nGenPar',
             'genParId',
             'genMomParId',
             'genParSt',
             'genParPx',
             'genParPy',
             'genParPz',
             'genParE',

             'THINnJet',
             'THINjetPx',
             'THINjetPy',
             'THINjetPz',
             'THINjetEnergy',
             'THINjetPassIDLoose',
             'THINjetDeepCSV_b',
             'THINjetHadronFlavor',
             ]
